site_name: MS Power Platform Info
site_url: https://warwickofthegh.github.io/mspowerplatform.info/
repo_url: https://github.com/warwickofthegh/mspowerplatform.info
repo_name: Github
edit_uri: edit/main/docs/

# nav:
#   - Calculation Docs: index.md
#   - tutorials.md
#   - How-To Guides: how-to-guides.md
#   - reference.md
#   - explanation.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  #logo: assets/logo.png
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   primary: custom
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny-off
        name: Switch to system preference

  # - scheme: default
  #   toggle:
  #     icon: material/brightness-4
  #     name: Switch to dark mode
  #   primary: teal
  #   accent: purple 

  # - scheme: slate 
  #   toggle:
  #     icon: material/brightness-7
  #     name: Switch to light mode    
  #   primary: teal
  #   accent: lime

plugins:
  - search
  - git-revision-date-localized:
      #enabled: !ENV [CI, false]
      enable_creation_date: false
  - git-committers:
        repository: warwickofthegh/mspowerplatform.info
        branch: main
        #enabled: !ENV [CI, false]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# copyright: |
#   &copy; 2023 <a href="https://github.com/warwickofthegh"  target="_blank" rel="noopener">Warwick</a>

